### ISSUE TITLE
idea: Merge colors

### ISSUE THREAD

**Issue by qkzk** [qkzk/fm#96]
All colors should be in a single item : 

```yaml 
colors:
   directory: blue
   normal_start: red
   normal_end: blue
   innert_border: grey
   palette1 etc.
```

Breaks config :(
